ansible_connection: httpapi
ansible_network_os: eos
ansible_user: arista
ansible_ssh_pass: arista
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
local_users:
  arista:
    privilege: 15
    role: network-admin
    sha512_password: $6$65WelVlMdQ5fTGDP$G5HfqPlZwNl2FePG38sSMh5QfY/OWiVDeqYqkU1vBnPU0wswN0LXf6gRbsQCd4eEH.tvzRsZj3B2SuQ3kQQe01
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
cvp_instance_ip: 192.168.0.5
cvp_ingestauth_key: ''
mgmt_gateway: 10.255.105.193
mgmt_interface_vrf: MGMT
eos_config_deploy_eapi_pre_running_config_backup: true
name_servers:
- 192.168.2.1
- 8.8.8.8
fabric_name: AVD_FABRIC
underlay_p2p_network_summary: 172.31.255.0/24
overlay_loopback_network_summary: 192.168.255.0/24
vtep_loopback_network_summary: 192.168.254.0/24
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24
vxlan_vlan_aware_bundles: true
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: AQQvKeimxJu+uGQ/yYvv9w==
  EVPN_OVERLAY_PEERS:
    password: q+VNViP5i4rVjW1cxFv2wA==
  MLAG_IPv4_UNDERLAY_PEER:
    password: vnEaG8gMeQf3d3cN6PktXQ==
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  leaf_as_range: 65101-65132
  nodes:
    AVD-SPINE1:
      id: 1
      mgmt_ip: 192.168.0.1/24
    AVD-SPINE2:
      id: 2
      mgmt_ip: 192.168.0.2/24
l3leaf:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as: 65100
    spines:
    - AVD-SPINE1
    - AVD-SPINE2
    uplink_to_spine_interfaces:
    - Ethernet3
    - Ethernet4
    mlag_interfaces:
    - Ethernet1
    - Ethernet2
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    AVD_LEAF1:
      bgp_as: 65101
      nodes:
        AVD-LEAF1A:
          id: 1
          mgmt_ip: 192.168.0.11/24
          spine_interfaces:
          - Ethernet2
          - Ethernet2
        AVD-LEAF1B:
          id: 2
          mgmt_ip: 192.168.0.12/24
          spine_interfaces:
          - Ethernet3
          - Ethernet3
    AVD_LEAF2:
      bgp_as: 65102
      nodes:
        AVD-LEAF2A:
          id: 3
          mgmt_ip: 192.168.0.13/24
          spine_interfaces:
          - Ethernet4
          - Ethernet4
        AVD-LEAF2B:
          id: 4
          mgmt_ip: 192.168.0.14/24
          spine_interfaces:
          - Ethernet5
          - Ethernet5
spine_bgp_defaults:
- no bgp default ipv4-unicast
- distance bgp 20 200 200
- graceful-restart restart-time 300
- graceful-restart
leaf_bgp_defaults:
- no bgp default ipv4-unicast
- distance bgp 20 200 200
- graceful-restart restart-time 300
- graceful-restart
p2p_uplinks_mtu: 1500
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
type: spine
inventory_file: /projects/second_proj/inventory/inventory.yml
inventory_dir: /projects/second_proj/inventory
ansible_host: 10.255.112.247
inventory_hostname: AVD-SPINE1
inventory_hostname_short: AVD-SPINE1
group_names:
- AVD
- AVD_FABRIC
- AVD_SPINES
ansible_facts:
  switch:
    underlay_routing_protocol: ebgp
    overlay_routing_protocol: ebgp
    id: 1
    mgmt_ip: 192.168.0.1/24
    spanning_tree_mode: none
    bgp_defaults:
    - no bgp default ipv4-unicast
    - distance bgp 20 200 200
    - graceful-restart restart-time 300
    - graceful-restart
    max_spines: 2
    platform: vEOS-LAB
    platform_settings:
      platforms:
      - default
      reload_delay:
        mlag: 300
        non_mlag: 330
    router_id: 192.168.255.1
    loopback_network_summary: 192.168.255.0/24
    bgp_as: 65001
    uplink_interfaces: []
    uplink_switches: []
    uplink_switch_interfaces: []
    isis_net: 49.0001.0001.0000.0001.00
    evpn_role: server
    evpn_route_servers: []
  topology:
    peers: []
switch:
  underlay_routing_protocol: ebgp
  overlay_routing_protocol: ebgp
  id: 1
  mgmt_ip: 192.168.0.1/24
  spanning_tree_mode: none
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  max_spines: 2
  platform: vEOS-LAB
  platform_settings:
    platforms:
    - default
    reload_delay:
      mlag: 300
      non_mlag: 330
  router_id: 192.168.255.1
  loopback_network_summary: 192.168.255.0/24
  bgp_as: 65001
  uplink_interfaces: []
  uplink_switches: []
  uplink_switch_interfaces: []
  isis_net: 49.0001.0001.0000.0001.00
  evpn_role: server
  evpn_route_servers: []
topology:
  peers: []
playbook_dir: /projects/second_proj/playbooks
ansible_playbook_python: /usr/local/bin/python
ansible_config_file: /projects/second_proj/ansible.cfg
groups:
  all:
  - cv_ztp
  - cv_server
  - AVD-SPINE1
  - AVD-SPINE2
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  ungrouped: []
  CVP:
  - cv_ztp
  - cv_server
  AVD:
  - AVD-SPINE1
  - AVD-SPINE2
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_FABRIC:
  - AVD-SPINE1
  - AVD-SPINE2
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_SPINES:
  - AVD-SPINE1
  - AVD-SPINE2
  AVD_L3LEAFS:
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_LEAF1:
  - AVD-LEAF1A
  - AVD-LEAF1B
  AVD_LEAF2:
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_TENANTS_NETWORKS:
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_SERVERS:
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
omit: __omit_place_holder__36dc927d7a58ebb242c72fd22505b3a61964f74c
ansible_version:
  string: 2.10.12
  full: 2.10.12
  major: 2
  minor: 10
  revision: 12
ansible_check_mode: false
ansible_diff_mode: false
ansible_forks: 5
ansible_inventory_sources:
- /projects/second_proj/inventory/inventory.yml
ansible_skip_tags: []
ansible_run_tags:
- build
ansible_verbosity: 0
