ansible_connection: httpapi
ansible_network_os: eos
ansible_user: arista
ansible_ssh_pass: arista
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
local_users:
  arista:
    privilege: 15
    role: network-admin
    sha512_password: $6$65WelVlMdQ5fTGDP$G5HfqPlZwNl2FePG38sSMh5QfY/OWiVDeqYqkU1vBnPU0wswN0LXf6gRbsQCd4eEH.tvzRsZj3B2SuQ3kQQe01
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
cvp_instance_ip: 192.168.0.5
cvp_ingestauth_key: ''
mgmt_gateway: 10.255.105.193
mgmt_interface_vrf: MGMT
eos_config_deploy_eapi_pre_running_config_backup: true
name_servers:
- 192.168.2.1
- 8.8.8.8
fabric_name: AVD_FABRIC
underlay_p2p_network_summary: 172.31.255.0/24
overlay_loopback_network_summary: 192.168.255.0/24
vtep_loopback_network_summary: 192.168.254.0/24
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24
vxlan_vlan_aware_bundles: true
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: AQQvKeimxJu+uGQ/yYvv9w==
  EVPN_OVERLAY_PEERS:
    password: q+VNViP5i4rVjW1cxFv2wA==
  MLAG_IPv4_UNDERLAY_PEER:
    password: vnEaG8gMeQf3d3cN6PktXQ==
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  leaf_as_range: 65101-65132
  nodes:
    AVD-SPINE1:
      id: 1
      mgmt_ip: 192.168.0.1/24
    AVD-SPINE2:
      id: 2
      mgmt_ip: 192.168.0.2/24
l3leaf:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as: 65100
    spines:
    - AVD-SPINE1
    - AVD-SPINE2
    uplink_to_spine_interfaces:
    - Ethernet3
    - Ethernet4
    mlag_interfaces:
    - Ethernet1
    - Ethernet2
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    AVD_LEAF1:
      bgp_as: 65101
      nodes:
        AVD-LEAF1A:
          id: 1
          mgmt_ip: 192.168.0.11/24
          spine_interfaces:
          - Ethernet2
          - Ethernet2
        AVD-LEAF1B:
          id: 2
          mgmt_ip: 192.168.0.12/24
          spine_interfaces:
          - Ethernet3
          - Ethernet3
    AVD_LEAF2:
      bgp_as: 65102
      nodes:
        AVD-LEAF2A:
          id: 3
          mgmt_ip: 192.168.0.13/24
          spine_interfaces:
          - Ethernet4
          - Ethernet4
        AVD-LEAF2B:
          id: 4
          mgmt_ip: 192.168.0.14/24
          spine_interfaces:
          - Ethernet5
          - Ethernet5
spine_bgp_defaults:
- no bgp default ipv4-unicast
- distance bgp 20 200 200
- graceful-restart restart-time 300
- graceful-restart
leaf_bgp_defaults:
- no bgp default ipv4-unicast
- distance bgp 20 200 200
- graceful-restart restart-time 300
- graceful-restart
p2p_uplinks_mtu: 1500
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3
port_profiles:
  TENANT_A_B:
    mode: trunk
    vlans: 110-111,210-211
  TENANT_A:
    mode: access
    vlans: '110'
  TENANT_B:
    mode: trunk
    vlans: 210-211
servers:
  server01:
    rack: RackA
    adapters:
    - type: nic
      server_ports:
      - Ethernet1
      - Ethernet2
      switch_ports:
      - Ethernet11
      - Ethernet11
      switches:
      - AVD-LEAF1A
      - AVD-LEAF1B
      profile: TENANT_A
  server02:
    rack: RackA
    adapters:
    - type: nic
      server_ports:
      - Ethernet2
      - Ethernet1
      switch_ports:
      - Ethernet12
      - Ethernet12
      switches:
      - AVD-LEAF1A
      - AVD-LEAF1B
      profile: TENANT_A
tenants:
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      Tenant_A_OP_Zone:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.254.1.0/24
        svis:
          12:
            name: Tenant_A_OP_Zone_Test
            tags:
            - opzone
            enabled: true
            ip_subnet: 172.16.112.0/24
          110:
            name: Tenant_A_OP_Zone_1
            tags:
            - opzone
            enabled: true
            ip_subnet: 10.1.10.0/24
          111:
            vni_override: 50111
            name: Tenant_A_OP_Zone_2
            tags:
            - opzone
            enabled: true
            ip_subnet: 10.1.11.0/24
          112:
            vni_override: 50112
            name: Tenant_A_OP_Zone_3
            tags:
            - opzone
            enabled: true
            ip_subnet: 10.1.12.0/24
      Tenant_A_WEB_Zone:
        vrf_vni: 11
        svis:
          120:
            name: Tenant_A_WEB_Zone_1
            tags:
            - web
            - erp1
            enabled: true
            ip_subnet: 10.1.20.0/24
          121:
            name: Tenant_A_WEBZone_2
            tags:
            - web
            enabled: true
            ip_subnet: 10.1.21.0/24
      Tenant_A_APP_Zone:
        vrf_vni: 12
        svis:
          130:
            name: Tenant_A_APP_Zone_1
            tags:
            - app
            - erp1
            enabled: true
            ip_subnet: 10.1.30.0/24
          131:
            name: Tenant_A_APP_Zone_2
            tags:
            - app
            enabled: true
            ip_subnet: 10.1.31.0/24
      Tenant_A_DB_Zone:
        vrf_vni: 13
        svis:
          140:
            name: Tenant_A_DB_BZone_1
            tags:
            - db
            - erp1
            enabled: true
            ip_subnet: 10.1.40.0/24
          141:
            name: Tenant_A_DB_Zone_2
            tags:
            - db
            enabled: true
            ip_subnet: 10.1.41.0/24
      Tenant_A_WAN_Zone:
        vrf_vni: 14
        svis:
          150:
            name: Tenant_A_WAN_Zone_1
            tags:
            - wan
            enabled: true
            ip_subnet: 10.1.40.0/24
    l2vlans:
      160:
        vni_override: 55160
        name: Tenant_A_VMOTION
        tags:
        - vmotion
      161:
        name: Tenant_A_NFS
        tags:
        - nfs
  Tenant_B:
    mac_vrf_vni_base: 20000
    vrfs:
      Tenant_B_OP_Zone:
        vrf_vni: 20
        svis:
          210:
            name: Tenant_B_OP_Zone_1
            tags:
            - opzone
            enabled: true
            ip_subnet: 10.2.10.0/24
          211:
            name: Tenant_B_OP_Zone_2
            tags:
            - opzone
            enabled: true
            ip_subnet: 10.2.11.0/24
      Tenant_B_WAN_Zone:
        vrf_vni: 21
        svis:
          250:
            name: Tenant_B_WAN_Zone_1
            tags:
            - wan
            enabled: true
            ip_subnet: 10.2.50.0/24
  Tenant_C:
    mac_vrf_vni_base: 30000
    vrfs:
      Tenant_C_OP_Zone:
        vrf_vni: 30
        svis:
          310:
            name: Tenant_C_OP_Zone_1
            tags:
            - opzone
            enabled: true
            ip_subnet: 10.3.10.0/24
          311:
            name: Tenant_C_OP_Zone_2
            tags:
            - opzone
            enabled: true
            ip_subnet: 10.3.11.0/24
      Tenant_C_WAN_Zone:
        vrf_vni: 31
        svis:
          350:
            name: Tenant_C_WAN_Zone_1
            tags:
            - wan
            enabled: true
            ip_subnet: 10.3.50.0/24
type: l3leaf
inventory_file: /projects/second_proj/inventory/inventory.yml
inventory_dir: /projects/second_proj/inventory
ansible_host: 10.255.31.199
inventory_hostname: AVD-LEAF2B
inventory_hostname_short: AVD-LEAF2B
group_names:
- AVD
- AVD_FABRIC
- AVD_L3LEAFS
- AVD_LEAF2
- AVD_SERVERS
- AVD_TENANTS_NETWORKS
ansible_facts:
  switch:
    underlay_routing_protocol: ebgp
    overlay_routing_protocol: ebgp
    group: AVD_LEAF2
    id: 4
    mgmt_ip: 192.168.0.14/24
    platform: vEOS-LAB
    platform_settings:
      platforms:
      - default
      reload_delay:
        mlag: 300
        non_mlag: 330
    configure_tenants: true
    filter_tenants:
    - all
    igmp_snooping_enabled: true
    filter_tags:
    - all
    max_spines: 2
    uplink_switches:
    - AVD-SPINE1
    - AVD-SPINE2
    uplink_switch_interfaces:
    - Ethernet5
    - Ethernet5
    uplink_interfaces:
    - Ethernet3
    - Ethernet4
    router_id: 192.168.255.6
    loopback_network_summary: 192.168.255.0/24
    bgp_as: 65102
    bgp_defaults:
    - no bgp default ipv4-unicast
    - distance bgp 20 200 200
    - graceful-restart restart-time 300
    - graceful-restart
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    mlag_ibgp_origin_incomplete: true
    mlag: true
    mlag_l3: true
    mlag_group: AVD_LEAF2
    mlag_peer_l3_vlan: 4093
    mlag_peer_vlan: 4094
    mlag_dual_primary_detection: false
    mlag_interfaces:
    - Ethernet1
    - Ethernet2
    mlag_role: secondary
    mlag_peer: AVD-LEAF2A
    mlag_peer_mgmt_ip: 192.168.0.13
    mlag_ip: 10.255.252.5
    mlag_peer_ip: 10.255.252.4
    mlag_l3_ip: 10.255.251.5
    mlag_peer_l3_ip: 10.255.251.4
    vtep_ip: 192.168.254.5
    evpn_services_l2_only: false
    evpn_role: client
    evpn_route_servers:
    - AVD-SPINE1
    - AVD-SPINE2
    isis_net: 49.0001.0001.0001.0004.00
    tenants:
      Tenant_A:
        vrfs:
          Tenant_A_APP_Zone:
            svis:
            - 130
            - 131
          Tenant_A_DB_Zone:
            svis:
            - 140
            - 141
          Tenant_A_OP_Zone:
            svis:
            - 12
            - 110
            - 111
            - 112
          Tenant_A_WAN_Zone:
            svis:
            - 150
          Tenant_A_WEB_Zone:
            svis:
            - 120
            - 121
        l2vlans:
        - 160
        - 161
      Tenant_B:
        vrfs:
          Tenant_B_OP_Zone:
            svis:
            - 210
            - 211
          Tenant_B_WAN_Zone:
            svis:
            - 250
        l2vlans: []
      Tenant_C:
        vrfs:
          Tenant_C_OP_Zone:
            svis:
            - 310
            - 311
          Tenant_C_WAN_Zone:
            svis:
            - 350
        l2vlans: []
    vlans:
    - 130
    - 131
    - 140
    - 141
    - 12
    - 110
    - 111
    - 112
    - 150
    - 120
    - 121
    - 160
    - 161
    - 210
    - 211
    - 250
    - 310
    - 311
    - 350
  topology:
    links:
      Ethernet3:
        peer: AVD-SPINE1
        peer_interface: Ethernet5
        peer_type: spine
        peer_bgp_as: 65001
        type: underlay_p2p
        ip_address: 172.31.255.13
        peer_ip_address: 172.31.255.12
      Ethernet4:
        peer: AVD-SPINE2
        peer_interface: Ethernet5
        peer_type: spine
        peer_bgp_as: 65001
        type: underlay_p2p
        ip_address: 172.31.255.15
        peer_ip_address: 172.31.255.14
    peers:
    - AVD-SPINE1
    - AVD-SPINE2
switch:
  underlay_routing_protocol: ebgp
  overlay_routing_protocol: ebgp
  group: AVD_LEAF2
  id: 4
  mgmt_ip: 192.168.0.14/24
  platform: vEOS-LAB
  platform_settings:
    platforms:
    - default
    reload_delay:
      mlag: 300
      non_mlag: 330
  configure_tenants: true
  filter_tenants:
  - all
  igmp_snooping_enabled: true
  filter_tags:
  - all
  max_spines: 2
  uplink_switches:
  - AVD-SPINE1
  - AVD-SPINE2
  uplink_switch_interfaces:
  - Ethernet5
  - Ethernet5
  uplink_interfaces:
  - Ethernet3
  - Ethernet4
  router_id: 192.168.255.6
  loopback_network_summary: 192.168.255.0/24
  bgp_as: 65102
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  virtual_router_mac_address: 00:1c:73:00:dc:01
  spanning_tree_mode: mstp
  spanning_tree_priority: 4096
  mlag_ibgp_origin_incomplete: true
  mlag: true
  mlag_l3: true
  mlag_group: AVD_LEAF2
  mlag_peer_l3_vlan: 4093
  mlag_peer_vlan: 4094
  mlag_dual_primary_detection: false
  mlag_interfaces:
  - Ethernet1
  - Ethernet2
  mlag_role: secondary
  mlag_peer: AVD-LEAF2A
  mlag_peer_mgmt_ip: 192.168.0.13
  mlag_ip: 10.255.252.5
  mlag_peer_ip: 10.255.252.4
  mlag_l3_ip: 10.255.251.5
  mlag_peer_l3_ip: 10.255.251.4
  vtep_ip: 192.168.254.5
  evpn_services_l2_only: false
  evpn_role: client
  evpn_route_servers:
  - AVD-SPINE1
  - AVD-SPINE2
  isis_net: 49.0001.0001.0001.0004.00
  tenants:
    Tenant_A:
      vrfs:
        Tenant_A_APP_Zone:
          svis:
          - 130
          - 131
        Tenant_A_DB_Zone:
          svis:
          - 140
          - 141
        Tenant_A_OP_Zone:
          svis:
          - 12
          - 110
          - 111
          - 112
        Tenant_A_WAN_Zone:
          svis:
          - 150
        Tenant_A_WEB_Zone:
          svis:
          - 120
          - 121
      l2vlans:
      - 160
      - 161
    Tenant_B:
      vrfs:
        Tenant_B_OP_Zone:
          svis:
          - 210
          - 211
        Tenant_B_WAN_Zone:
          svis:
          - 250
      l2vlans: []
    Tenant_C:
      vrfs:
        Tenant_C_OP_Zone:
          svis:
          - 310
          - 311
        Tenant_C_WAN_Zone:
          svis:
          - 350
      l2vlans: []
  vlans:
  - 130
  - 131
  - 140
  - 141
  - 12
  - 110
  - 111
  - 112
  - 150
  - 120
  - 121
  - 160
  - 161
  - 210
  - 211
  - 250
  - 310
  - 311
  - 350
topology:
  links:
    Ethernet3:
      peer: AVD-SPINE1
      peer_interface: Ethernet5
      peer_type: spine
      peer_bgp_as: 65001
      type: underlay_p2p
      ip_address: 172.31.255.13
      peer_ip_address: 172.31.255.12
    Ethernet4:
      peer: AVD-SPINE2
      peer_interface: Ethernet5
      peer_type: spine
      peer_bgp_as: 65001
      type: underlay_p2p
      ip_address: 172.31.255.15
      peer_ip_address: 172.31.255.14
  peers:
  - AVD-SPINE1
  - AVD-SPINE2
playbook_dir: /projects/second_proj/playbooks
ansible_playbook_python: /usr/local/bin/python
ansible_config_file: /projects/second_proj/ansible.cfg
groups:
  all:
  - cv_ztp
  - cv_server
  - AVD-SPINE1
  - AVD-SPINE2
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  ungrouped: []
  CVP:
  - cv_ztp
  - cv_server
  AVD:
  - AVD-SPINE1
  - AVD-SPINE2
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_FABRIC:
  - AVD-SPINE1
  - AVD-SPINE2
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_SPINES:
  - AVD-SPINE1
  - AVD-SPINE2
  AVD_L3LEAFS:
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_LEAF1:
  - AVD-LEAF1A
  - AVD-LEAF1B
  AVD_LEAF2:
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_TENANTS_NETWORKS:
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
  AVD_SERVERS:
  - AVD-LEAF1A
  - AVD-LEAF1B
  - AVD-LEAF2A
  - AVD-LEAF2B
omit: __omit_place_holder__36dc927d7a58ebb242c72fd22505b3a61964f74c
ansible_version:
  string: 2.10.12
  full: 2.10.12
  major: 2
  minor: 10
  revision: 12
ansible_check_mode: false
ansible_diff_mode: false
ansible_forks: 5
ansible_inventory_sources:
- /projects/second_proj/inventory/inventory.yml
ansible_skip_tags: []
ansible_run_tags:
- build
ansible_verbosity: 0
