---
# Validation lab
# local users
local_users:
  arista:
    privilege: 15
    role: network-admin
    sha512_password: "$6$65WelVlMdQ5fTGDP$G5HfqPlZwNl2FePG38sSMh5QfY/OWiVDeqYqkU1vBnPU0wswN0LXf6gRbsQCd4eEH.tvzRsZj3B2SuQ3kQQe01"

  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

# OOB Management network default gateway.
mgmt_gateway: 10.255.105.193
mgmt_interface_vrf: default

# Peform config backup before config replace
eos_config_deploy_eapi_pre_running_config_backup: true

# dns servers.
name_servers:
  - 192.168.2.1
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
# ntp_servers:
#  - 192.168.0.2
#  - 192.168.0.3
